#!/usr/bin/env bash
set -euo pipefail

: "${DATABASE_URL:?DATABASE_URL is required}"
: "${R2_ACCOUNT_ID:?R2_ACCOUNT_ID is required}"
: "${R2_ACCESS_KEY_ID:?R2_ACCESS_KEY_ID is required}"
: "${R2_SECRET_ACCESS_KEY:?R2_SECRET_ACCESS_KEY is required}"
: "${R2_BUCKET:?R2_BUCKET is required}"
: "${R2_ENDPOINT_URL:?R2_ENDPOINT_URL is required}"
: "${REPLICATE_API_TOKEN:?REPLICATE_API_TOKEN is required}"
: "${FRONTEND_ORIGIN:?FRONTEND_ORIGIN is required}"

cat <<EOF
APP_ENV: "production"
API_PORT: "8080"
FRONTEND_ORIGIN: "${FRONTEND_ORIGIN}"
DATABASE_URL: "${DATABASE_URL}"
R2_ACCOUNT_ID: "${R2_ACCOUNT_ID}"
R2_ACCESS_KEY_ID: "${R2_ACCESS_KEY_ID}"
R2_SECRET_ACCESS_KEY: "${R2_SECRET_ACCESS_KEY}"
R2_BUCKET: "${R2_BUCKET}"
R2_PUBLIC_BASE_URL: "${R2_PUBLIC_BASE_URL:-}"
R2_ENDPOINT_URL: "${R2_ENDPOINT_URL}"
R2_REGION: "${R2_REGION:-auto}"
REPLICATE_API_TOKEN: "${REPLICATE_API_TOKEN}"
EOF
